environment:
    CYG_MIRROR: http://cygwin.mirror.constant.com
    CYG_PACKAGES: make,gcc-core,clang,mingw64-i686-gcc-core,mingw64-x86_64-gcc-core
    matrix:
        - MSYSTEM: MINGW64
          BASH: C:\msys64\usr\bin\bash
          MSYS_CACHE: C:\msys64\var\cache\pacman\pkg
        - MSYSTEM: MINGW32
          BASH: C:\msys64\usr\bin\bash
          MSYS_CACHE: C:\msys64\var\cache\pacman\pkg
        - CYG_ROOT: C:\cygwin64
          CYG_CACHE: C:\cygwin64\var\cache\setup
          CYG_SETUP: setup-x86_64.exe
          BASH: C:\cygwin64\bin\bash
        - CYG_ROOT: C:\cygwin
          CYG_CACHE: C:\cygwin\var\cache\setup
          CYG_SETUP: setup-x86.exe
          BASH: C:\cygwin\bin\bash

# Cache Cygwin/MSYS files to speed up build
cache:
    - '%CYG_CACHE%'
    - '%MSYS_CACHE%'
clone_depth: 1

# Attempt to ensure we don't try to convert line endings to Win32 CRLF as this will cause build to fail
init:
    - git config --global core.autocrlf input
# Allows RDP
#    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Install needed build dependencies
install:
    - ps: if (Test-Path Env:\CYG_ROOT) { Start-FileDownload "http://cygwin.com/$env:CYG_SETUP" -FileName "$env:CYG_SETUP" }
    - if defined CYG_ROOT (%CYG_SETUP% --quiet-mode --no-shortcuts --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_CACHE%" --packages "%CYG_PACKAGES%" --upgrade-also)
    - if defined MSYSTEM (%BASH% -lc "pacman -Suuy --noconfirm")
    - if defined MSYSTEM (%BASH% -lc "pacman -Suuy --noconfirm")
build_script:
    - if defined BASH (%BASH% -lc "cd $(cygpath ${APPVEYOR_BUILD_FOLDER}) && git submodule init && git submodule update && make")
# Allows RDP
#on_finish:
#    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
